### ISSUE TITLE
Enabling 'Extra cool effects' give weird depth of field

### ISSUE THREAD

**Issue by Skryptonyte** [VFansss/mgs2-v-s-fix#43]
I notice that on a lot of cutscenes, at times there is some weird kind of graphical anomaly that occurs in characters at times like the edge of a character seems to be like cloned a few times. Dont know how to call it.

I think it might be DoF or Motion Blur or something not working properly. Is this what youd call a "Complain Konami" issue.

I have a GTX 750 Ti and i3 4170, running on Windows 10, 1080p 16:9. Everything enabled except model quality set to medium

**Comment by Skryptonyte** [comment]
![screenshot 15](https://user-images.githubusercontent.com/40635533/42041232-196a2c36-7b0f-11e8-9c51-b9c4f9f73029.png)

So I went through the changelogs, and I think I am using v1.05.2. So maybe that version has the issue, because I dont see anyone else reporting it, I searched up and got nothing. Maybe v1.04 which is supposed to be the stable version wont have it?

It seems it is less noticable when lowering the resolution. I think if you go down to 480p which was the resolution of the XBOX port, it's probably hardly noticable. I suppose DoF doesnt scale well to high resolutions.

**Comment by VFansss** [comment]
> So I went through the changelogs, and I think I am using v1.05.2.

I've asked because I've released the 1.05.2 prematurely, and is downloadable only from the release tab, but I've discouraged to download it!

>  It seems it is less noticable when lowering the resolution. I think if you go down to 480p which was the resolution of the XBOX port, it's probably hardly noticable. I suppose DoF doesnt scale well to high resolutions.

Well, I finished the game several times at 720p and 1080p and I didn't never experienced this.

Another user has reported [something similar](https://github.com/VFansss/mgs2-v-s-fix/issues/34) in the past, but the user didn't answered enough to definitively debug what's happened.

You have an NVidia, uh? Please post me the [debug file](https://github.com/VFansss/mgs2-v-s-fix/wiki/Troubleshooting-&-Debug-mode#debug-mode) and the last.log file that you could find inside the main game folder. Maybe this time I can debug whatever is causing that ugly things...

Also, to solve the issue, you can try to apply the mgs2_sse.exe posted in the issue #34 . Tell me if its working!

**Comment by Skryptonyte** [comment]
[last.log](https://github.com/VFansss/mgs2-v-s-fix/files/2149294/last.log)
[MGS2_VFix_debug.txt](https://github.com/VFansss/mgs2-v-s-fix/files/2149296/MGS2_VFix_debug.txt)

How do I downgrade to v1.04 then?

**Comment by VFansss** [comment]
Before doing everything just try the solution I mentioned above: download [THIS](https://drive.google.com/file/d/1mKgV204_z2z-f3PBm7vMBkdhXr91JoQh/view) and extract it inside the game folder, and overwrite.

Then start the game from mgs2_sse,exe, and tell me if something goes wrong.

> How do I downgrade to v1.04 then?

Simply download it [here](https://github.com/VFansss/mgs2-v-s-fix/releases/download/v1.04/MGS.V.s.Fix.v1.04.zip)

**Comment by Skryptonyte** [comment]
So I simple just overwrite the setup exe with the v1.04 one, that's it? I am asking because I don't want to run into issues. 

Also, I will try out that mgs2_sse.exe first

**Comment by Skryptonyte** [comment]
[MGS2_VFix_debug.txt](https://github.com/VFansss/mgs2-v-s-fix/files/2149400/MGS2_VFix_debug.txt)

Also, I tried out the exe which you suggested but the issue is still there. Additionally, the image seems a bit more stretched than usual (16:9 not working well).

**Comment by VFansss** [comment]
This is a tough one to debug... please try the 1.04 version and report me back!

**Comment by Skryptonyte** [comment]
I just tried it and the same issue persists.

**Comment by VFansss** [comment]
Try to go inside V's Fix Settings inside Graphic tab and disable Motion Blur and Anti-Aliasing

**Comment by Skryptonyte** [comment]
Issue still there on v1.04 with AA and Blur disabled

**Comment by VFansss** [comment]
I have to be totally honest: I don't have an idea :|

All seems ok: the VGA is correctly recognized, the filters are off. There is nothing else that could make some issues.

Try to disable the Widescreen fix and do a last try, please :disappointed:

**Comment by Skryptonyte** [comment]
Disabling 16:9

Sadly, issue still persists. I guess this is some kind of a weird isolated case?

**Comment by VFansss** [comment]
I have to be totally honest: I don't know.

Probably is something on your config that is making that particular issues.

You solved that somehow?

**Comment by VFansss** [comment]
I was pretty sure that I have answered, but I did not. Sorry 😢 

You can try the last build of the fix (1.06) to see if the things has been solved. I have changed something that could have been solved the issue.

Also, I will continue to investigate on that. Meanwhile you can continue playing with 'Cool effects' disabled: I never truly understand what "Stealth/VR Effects" do, so I don't think do you will notice any difference!

If you do, please message be, because I'm truly curious to understand what they do 😄

**Comment by VFansss** [comment]
Now I'm pretty busy, but I get an idea on how to solve this...

I will edit this message ASAP!

**Comment by VFansss** [comment]
Ok, I swear: I was very busy these days!

I've done some researches and I've updated my notes.

To solve this, you can do a simple test:

* Go to 'Graphics' tab and enable 'Extra cool effects'
* Press SAVE, open the game and choose a scene where the 'weird depth of field' is clearly visible.
* Close the game, than open mgs2.ini file.

You can see several couple of strings.

The 'Extra cool effects' enable (all at once) four kind of effects present in the original launcher.

The only way to solve this bug is...understand what is the effect that give that bug.

Inside your file you can find, on the "left" the 004-whatever opcodes, and of the right I've commented what they are doing.

0041 0001 // Stealth Effect
0042 0001 // Focus
0043 0001 // Codec Focus
004A 0001 // VR MODE

Simply start from the first one, and remove it from the mgs2.ini file (simply delete the row). For example to test Stealth Effect this is part of the file BEFORE editing it:

```
0049	0100
0047	0001
0041	0001
0042	0001
0043	0001
004A	0001
0044	0001
0045	0001
0090	5072696D
0091	61727920
0092	536F756E
```

and this is the same part after you deleted the Stealth Effect:

`0049	0100
0047	0001
0042	0001
0043	0001
004A	0001
0044	0001
0045	0001
0090	5072696D
0091	61727920
0092	536F756E`

As you can see the '0041 0001' row has been deleted, and so also the 'Stealth Effect'

Then save the file, and start the game from mgs2_sse.exe and check if the bug is still there.

If yes -> We have understand what is causing that

If not -> Go to the next one and do that again:

* Close the game
* Open the mgs2.ini file
* Delete another one of the 3 remaining effect
* Check it again.

I know that this is tedious, but I don't have the bug so you are the only way to definitively understand what is causing it.

I'm sorry for the late reply, but I would be very happy to solve this :smile:

**Comment by Skryptonyte** [comment]
I've actually already done this. I removed the opcode corresponding to focus as listed in the opcode.txt beforehand. I did test with other 3 to see whether perhaps there are conflicting effects but nothing changes. Removing focus removes the depth of field altogether.

I am also using that same sample of the cutscene with ocelot and ames. I think this represents the worst case scenario of the broken DoF.

**Comment by VFansss** [comment]
Well, then I simply think its the depth of field that gave some sort of weird bug.

Now I've discovered that is under the 'Focus' option, so I can only make an extra trigger to disable it separately from the other 3 effect, because I don't truly have an idea on how to fix it :cry:

**Comment by Skryptonyte** [comment]
Hmm, that's a shame 😕

Maybe, it's an issue pertaining to certain GPU architectures methinks, like maybe Maxwell cards suffer from this bug.

**Comment by VFansss** [comment]
I'm glad we pinpointed the issue. In the past I've already encountered it ( Issue #34 ) but I was at least partially wrong on the solution. (Ok, I was truly wrong on that).

I split the Depth of Field from the Extra cool effects, so it can be disabled/enabled separately. At least stop the bleeding, until I find a proper solution.

I've also added it to the wiki, so it should be easier to pinpoint. If I can find the true culprit on that, I will gladly solve it once for all.

Thanks for reporting me 😄
